# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'допомога.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 651)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 16, 441, 551))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit.setTabChangesFocus(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButtonn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonn.setGeometry(QtCore.QRect(380, 580, 93, 28))
        self.pushButtonn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonn.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWhatsThis(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Вітаю вас у програмі реєстрації клієнтів!\n"
"В цьому додатку ви можете створити свій обліковий запис(1) або видалити його, якщо вже зареєстровані(2)\n"
"1.    Створення облікового запису\n"
"Після натискання «Зареєструватися» вам надається три текстові поля для введення свого імені, прізвища та по батькові. Ці данні мають складатися з букв українського або англійського алфавіту, перша з них – велика літера. Після введення даних в кожне поле ви повинні підтвердити введення, а в самому кінці натиснути «продовжити», щоб перейти до наступного етапу реєстрації. \n"
"Наступний крок вашої реєстрації – це введення логіну та паролю. Логін може містити в собі тільки букви, цифри та «_»  – нижнє підкреслювання. Пароль може складатися тільки з літер та цифр. В разі, якщо введені вами дані не підходять під вимоги програми, вам буде про це повідомлення у строці повідомлень. Після підтвердження вами введених даних, програма відображає ваш акаунт, як зареєстрований. В разі, якщо ви вже маєте обліковий запис, вам достатньо натиснути «увійти», після чого ввести логін та пароль від свого акаунту та потрапити до нього.\n"
"2.    Видалення облікового запису\n"
"Якщо ви бажаєте видалити свій обліковий запис, потрібно натиснути «Видалити обліковий запис». Після цього потрібно ввести свій логін та пароль. В разі, якщо вони вірні, програма повідомить, що ваш обліковий запис видалено, після чого ви потрапите на головне меню.\n"
"3.    Вхід\n"
"Якщо ви вже маєте обліковий запис, та бажаєте увійти до нього, потрібно натиснути «Увійти» та вам буде представлено сторінку для вводу ваших особистих даних. Достатньо ввести логін та пароль, які були створені під час реєстрації. Введені дані також будуть перевірені на співпадіння з уже наявними, після чого вам буде дозволено потрапити до облікового запису.\n"
""))
        self.pushButtonn.setText(_translate("MainWindow", "Назад"))
